### ISSUE TITLE
Output in English only?

### ISSUE THREAD

**Issue by phtmgt** [enhancedocs/enhancedocs#16]
I have the documentation in a language other than English. What happens is enhancedocs always replies in English, regardless of whether I ask the question in English or any other language, including the language of the original documentation. Is this expected behavior? It does not make any sense. The strength of LLMs is their ability to get prompts and answer in lots of languages.

**Comment by Alw3ys** [comment]
You can try tweking the `promp_template.txt` file https://github.com/enhancedocs/enhancedocs/blob/main/prompt_template.txt to your preferred language

**Comment by phtmgt** [comment]
> You can try tweking the `promp_template.txt` file https://github.com/enhancedocs/enhancedocs/blob/main/prompt_template.txt to your preferred language

I did just that, thanks.
