### ISSUE TITLE
Is the open-source part of this project dead/stalled?

### ISSUE THREAD

**Issue by phtmgt** [enhancedocs/enhancedocs#17]
So, currently, the frontend docusaurus integration does not work with the OS version of the deployed server. It is looking for an '/ask/stream' endpoint, which is non-existent on the OS version. Is this just a matter of 'delay' or is the project focusing on the commercial side? Of course, focusing on commercial is completely fine, but, please, be frank here and let us know - no-one wants to invest time and effort in something that becomes unusable down the line (been there, done that). This is especially important for bootstrapped projects that can't afford the 750/month on an annual basis.

**Comment by Alw3ys** [comment]
Hey, the project is not maintain either the commercial on open source, decided to make it open source so people could leverage it instead or just shutting it down. If open source and free, so if you want it to suit your needs you are more than welcome to change it, or use the source as inspiration
