### ISSUE TITLE
Unable to Ingest Markdown docs to EnhanceDocs managed successfully

### ISSUE THREAD

**Issue by bazhang87** [enhancedocs/enhancedocs#7]
Although I follow instructions for uploading my markdown docs to EnhanceDocs managed, setting my EnhanceDocs API_KEY environment variable (sk_***) and pushing to my project ID (which displays 'Uploading... Ingestion Finished' the project does not detect the document format, and does not show sources. Also can't query against document sources successfully. I get an html response back with a query.

<img width="1701" alt="test" src="https://user-images.githubusercontent.com/60352611/234170892-936e3569-1a0a-433a-9793-3ccd86bd8534.png">

**Comment by Alw3ys** [comment]
Hi @bazhang87!

 First of all apologies that your first experience was like this...

Two things. For enhancedocs managed you must provided a project id and I admit the the cli could be a bit more informative about that. Example `enhancedocs ask --project your_project_id write your question here`.

Our cli is still quite immature and we have on the roadmap to add maturity to it so it supports better arguments hopefully this will solve some of the bad user experience now there is currently.

but I'm going to take a look deeper and see how I can see what went wrong and improve the cli.

Would you mind sharing with me the following things?
1. If the documentation you are trying to push is public would you mind sharing a link so I can take a look for testing?
2. Mind sharing what params 
did you use to run `enhancedocs build` and which folder?

and thanks for opening the issue! EnhanceDocs still quite new and therefore a lot of work still yet to be done! but every single new issue opened and solved is a step closer to having a mature solution!

**Comment by Alw3ys** [comment]
Hey @bazhang87!

Just released a new version on python for the CLI, now it should support arguments and everything like a regular CLI with additional --help and all these issues of not readable files solved.

Check it out! https://github.com/enhancedocs/cli

This should solve your issue, I'll close it now, if you still experience any issues, feel free to re-open it.
